### ISSUE TITLE
'Unexpected token o' on requests

### ISSUE THREAD

**Issue by dgerrells** [hps/heartland-tokenization-jquery-library#18]
Following the example of iframe/jquery hybrid implementation example from https://github.com/hps/heartland-example-code and Heartland API docs, anytime the iframe form is submitted an 'Unexpected token o' is thrown. 

This happens becausea an object and not a string is passed into JOSN.parse on line 540:
```
            HPS.Messages.receiveMessage(function(m){
                var data = JSON.parse(m.data); //m.data is not a string
                switch(data.action) {
                    case 'tokenize': {
                        HPS.tokenize_iframe(data.message);
                        break;
                    }
                    case 'setStyle': {
                        HPS._setStyle(data.id, data.style);
                        HPS._resizeFrame();
                        break;
                    }
                    case 'appendStyle': {
                        HPS._appendStyle(data.id, data.style);
                        HPS._resizeFrame();
                        break;
                    }
                    case 'setText': {
                        HPS._setText(data.id, data.text);
                        HPS._resizeFrame();
                        break;
                    }
                    case 'setPlaceholder': {
                        HPS._setPlaceholder(data.id, data.text);
                        break;
                    }
                }
            }, '*');
```

[Here](https://jsfiddle.net/m5nwdzfc/) is a jsfiddle example. 

Looking at the commit history this was a recent change (last 14 days at the time of writing this) that changed/added the JSON.parse. The previous commit works as expected.

**Comment by slogsdon** [comment]
Thanks for the report, @dgerrells! From your jsfiddle, it looks like you're linking directly to the file on api.heartlandportico.com, correct? If so, we are waiting for our latest code (which has been pushed to hps.github.io) to be pushed to our production environment (api.heartlandportico.com), and this code push should correct your issue. In the meantime, you should be able to change the script's `src` attribute to point to `https://hps.github.io/token/2.0/securesubmit.js` to get around this issue.

This issue only affects cases where certification keys are being used and the linked script is on the api.heartlandportico.com domain as the Javascript will parse the cert key and loads the iframe on the hps.github.io domain, which loads the Javascript on that domain as well.

Let me know if this doesn't help you, and we can look into this further.

**Comment by dgerrells** [comment]
Thank you very much for getting back so quickly @slogsdon!

Indeed, changing the domain and pointing to ``` https://hps.github.io/token/2.0/securesubmit.js ``` worked. Not sure when to expect the change to move up to your production environment but this should allow me to continue work. I wouldn't mind knowing (if possible) when the push happens as I am not sure what the implications of not pointing to api.heartlandportico.com are. 

Thanks again.

**Comment by slogsdon** [comment]
@dgerrells Even if you kept your local script pointed to `hps.github.io`, all tokenization and user input would happen on `api.heartlandportico.com`. The local script reference just decides where the build process starts.

I'll follow up here once I hear word that the deployment is complete.

**Comment by slogsdon** [comment]
@dgerrells Actually, It looks like it should already be deployed. I didn't get a notification about it, but looking at [the code](https://api.heartlandportico.com/SecureSubmit.v1/token/2.0/securesubmit.js), it seems to be the latest copy. Let me know if you still have issues with it.

**Comment by dgerrells** [comment]
@slogsdon Yup pointing to ``` api.heartlandportico.com ``` works. Thanks for the help.

**Comment by slogsdon** [comment]
Not a problem!
